"use strict";
const test = require("node:test"); const assert = require("node:assert/strict"); const mongoose = require("mongoose");
const app = require("../../server"); const { User, ROLES } = require("../../src/modules/user/user.model");
const { Bet } = require("../../src/modules/bet/bet.model"); const SavedMatch = require("../../src/modules/saved-match/saved-match.model");
const { getSavedMatches } = require("../../src/modules/saved-match/saved-match.service"); const { generateAccessToken } = require("../../src/utils/generateToken");
const enabled = process.env.TEST_ALLOW_DB_WRITES === "true" && Boolean(process.env.TEST_MONGODB_URI); const stamp = Date.now(); const matchId = `combined-pnl-${stamp}`;
let server; let baseUrl; let superAdmin; let company; let user;
const auth = (actor) => ({ Authorization: `Bearer ${generateAccessToken({ id: actor._id, role: actor.role })}` });
test.before(async () => { if (!enabled) return; await mongoose.connect(process.env.TEST_MONGODB_URI);
  superAdmin = await User.create({ username: `pnlsa${stamp}`, password: "pass1234", role: ROLES.SUPERADMIN });
  company = await User.create({ username: `pnlco${stamp}`, password: "pass1234", role: ROLES.SUB_COMPANY, allocatedShareBps: 9500, createdBy: superAdmin._id, parentId: superAdmin._id, rootSuperAdminId: superAdmin._id });
  user = await User.create({ username: `pnlus${stamp}`, password: "pass1234", role: ROLES.USER, createdBy: company._id, parentId: company._id, rootSuperAdminId: superAdmin._id });
  await SavedMatch.create({ user: superAdmin._id, matchId, homeTeam: "A", awayTeam: "B", isDeclared: true, wonBy: "B", profitLoss: 100 });
  const common = { userId: user._id, rootSuperAdminId: superAdmin._id, ownerPath: [superAdmin._id, company._id], shareSnapshot: [{ userId: superAdmin._id, role: ROLES.SUPERADMIN, shareBps: 500 }, { userId: company._id, role: ROLES.SUB_COMPANY, shareBps: 9500 }], matchId, amount: 100, rate: 100, type: "yes", profit: 100, loss: 100 };
  await Bet.create([{ ...common, marketType: "match", marketId: "a", status: "lost" }, { ...common, marketType: "session", marketId: "s1", sessionRun: 10, sessionRate: 1, resultRun: 10, status: "won" }]);
  server = app.listen(0, "127.0.0.1"); await new Promise((resolve) => server.once("listening", resolve)); baseUrl = `http://127.0.0.1:${server.address().port}`;
});
test.after(async () => { if (!enabled) return; await new Promise((resolve) => server.close(resolve)); await Promise.all([Bet.deleteMany({ matchId }), SavedMatch.deleteMany({ matchId })]); await User.deleteMany({ _id: { $in: [superAdmin._id, company._id, user._id] } }); await mongoose.disconnect(); });
test("SuperAdmin combined P/L offsets match loss with session win", { skip: !enabled }, async () => { const match = (await getSavedMatches()).find((item) => item.matchId === matchId); assert.ok(match); assert.equal(match.profitLoss, 0); });
test("Sub Company sees combined match and session P/L at its share", { skip: !enabled }, async () => { const response = await fetch(`${baseUrl}/api/bet/company-match-summaries`, { headers: auth(company) }); const body = await response.json(); assert.equal(response.status, 200); assert.equal(body.data.find((item) => item.matchId === matchId).profitLoss, 0); });
test("Sub Company summary endpoint rejects unauthenticated and other roles", { skip: !enabled }, async () => { assert.equal((await fetch(`${baseUrl}/api/bet/company-match-summaries`)).status, 401); assert.equal((await fetch(`${baseUrl}/api/bet/company-match-summaries`, { headers: auth(superAdmin) })).status, 403); });
test("P/L stays hidden until the match itself is declared", { skip: !enabled }, async () => {
  await SavedMatch.updateOne({ matchId }, { $set: { isDeclared: false } });
  const superMatch = (await getSavedMatches()).find((item) => item.matchId === matchId);
  assert.equal(superMatch.profitLoss, null);
  const response = await fetch(`${baseUrl}/api/bet/company-match-summaries`, { headers: auth(company) });
  const companyMatch = (await response.json()).data.find((item) => item.matchId === matchId);
  assert.equal(companyMatch.profitLoss, null);
});
